#!/bin/bash

# Parameters: folders space separated
# E.g. : ./jtree ./src ./target

#########################################
# Check if Java is installed
#########################################
java_v=$(java --version)
if [ "$java_v" == "" ]; then
  echo ">> Java is not installed in your system!"
  echo ">> Please consider installing Java Runtime to execute this program."
  echo ">> https://openjdk.org/install/"
  exit 1
fi

#########################################
# Create jar
#########################################
ls ./target/jtree*-jar-with-dependencies.jar &> /dev/null

if [ "$?" -ne "0" ]; then
  ./mvnw clean package --file pom.xml &> /dev/null
fi

#########################################
# Run
#########################################
java -cp ./target/jtree*-jar-with-dependencies.jar com.suvmitra.jtree.JTreeKt "$@"